version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    environment:
      - DJANGO_SECRET_KEY=your_secret_key
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=techno_news_db
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"